### ISSUE TITLE
README outdated?

### ISSUE THREAD

**Issue by sappelhoff** [psychopy/pyosf#11]
In the README a basic example is:

```python
proj = pyosf.Project(project_file="/Home/myUserName/pyosfProjects/first.proj",
                       root_path="/Home/myUserName/experiments/firstExperiment",
                       osf=osf_proj)
changes = proj.analyze()  #so you can inspect them if needed
changes.apply()  #do the sync
proj.save()
```

However, when trying to run this I saw that `pyosf.Project` does not have a method `analyze`. What works instead is `get_changes`. Is the README perhaps outdated?

**Comment by peircej** [comment]
ah, yes, I think you're right. Feel free to change and I'll pull in your various fixes. Thanks
